### ISSUE TITLE
Ability to create foreign keys

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-generate#7]
Maybe an `--fks` option which causes some of the columns to randomly link to other existing tables with a foreign key relationship.

**Comment by simonw** [comment]
On Twitter: https://twitter.com/simonw/status/1275290155960561667

**Comment by simonw** [comment]
This can be the number of foreign key columns that should be created in each table, like `--rows`. So `--fks=1` means "one foreign key per table", but `--fks=0,3` means "between 0 and 3 foreign keys".

I'm going to keep things simple by saying foreign keys are always integers.

Rather than creating the foreign keys as part of the initial row insertion step, I'm going to add them as a second phase. This ensures tables can have circular references, and also means I can be more efficient in calculating random values - I can load the full set of primary keys for every table into memory (at worse a few Python arrays containing a million or so integer values) and use `random.choice()` against them to pick the linked rows.

**Comment by simonw** [comment]
I still want to add the columns at table creation time though. If I add them after the fact I can't easily control their order, and the simulated database will be less interesting to look at if the foreign key columns are all clustered at the ends of the tables.

I'll do that with a convention: a column can have an `_id` suffix which means it will be used as a foreign key.

**Comment by simonw** [comment]
The demo now includes foreign keys, e.g. https://sqlite-generate-demo.datasette.io/demo/economy_ago_fact

Here's an automatically generated table diagram showing those relationships: https://observablehq.com/@simonw/datasette-table-diagram?url=https%3A%2F%2Fsqlite-generate-demo.datasette.io%2Fdemo

![image](https://user-images.githubusercontent.com/9599/85420048-98323280-b527-11ea-8b11-4ed145fb5633.png)

**Comment by obi1kenobi** [comment]
This is awesome! 🎉  Thanks for putting it together!
