### ISSUE TITLE
Ability to create composite primary keys, or tables with no explicit primary key

### ISSUE THREAD

**Issue by obi1kenobi** [simonw/sqlite-generate#8]
Perhaps via a `--pks` option, to mirror the syntax in #7:
- `--pks=1` is the default, as I believe is currently the case.
- `--pks=0` results in tables that do not have a named column that could become an alias for the `ROWID`, meaning that SQLite adds its own implicit primary key column in addition to columns defined by the user. See SQLite docs for more detail here: https://www.sqlite.org/lang_createtable.html#rowid
- `--pks=2` results in tables that have a composite, two-column primary key. For simplicity of implementation, I'd say it's fine to mandate that components columns of the primary key are always of integer type.
- `--pks=0,2` means that tables may have between 0 and 2 named columns in the primary key, analogous to the syntax in #7.

Foreign keys to tables with composite primary keys would obviously have to be composite themselves, which would make the generation logic a bit trickier.

Tables with no explicit primary key cannot have other tables pointing to them via foreign keys, but may point to other tables via their own foreign keys.

**Comment by simonw** [comment]
This is a good idea. I think I'll punt on foreign key relationships to tables with compound primary keys, but supporting compound primary key tables and rowid tables is definitely feasible.

**Comment by simonw** [comment]
Released in 1.1. The demo at https://sqlite-generate-demo.datasette.io/ now demonstrates this feature.

**Comment by obi1kenobi** [comment]
This is awesome, thanks again for knocking this out so promptly!

Purely out of curiosity: I know that compound foreign keys would make the table-generation algorithm trickier (e.g., one would have to make sure that the foreign key "fits" in the allotted number of columns etc.) — is there an additional source of complexity that I'm missing as well? Obviously, feel free to ignore the question if it's too difficult and not worth explaining the answer, this is just for my curiosity.

**Comment by simonw** [comment]
It's mainly that neither of my [Datasette](https://github.com/simonw/datasette) or [sqlite-utils](https://github.com/simonw/sqlite-utils) projects support compound foreign keys which reduces my motivation to try and solve it here!

I wasn't even sure if they were a feature in SQLite, but it turns out they are: https://www.sqlite.org/foreignkeys.html#fk_composite - so maybe I'll figure them out some day in the future.

**Comment by simonw** [comment]
I filed an issue about this in sqlite-utils here: https://github.com/simonw/sqlite-utils/issues/117
